### ISSUE TITLE
Use Background Queue to not block the UI / response thread

### ISSUE THREAD

**Issue by TimWolla** [ChristopherWalz/wsc-connect-plugin#9]

**Comment by ChristopherWalz** [comment]
Are you talking about this https://github.com/ChristopherWalz/wsc-connect-plugin/blob/master/files/lib/system/event/listener/WSCConnectListener.class.php#L69 line?

**Comment by TimWolla** [comment]
Yes.

**Comment by ChristopherWalz** [comment]
Use case with the BackgroundQueueHandler: I visit a small site, which uses WSC-Connect, at night and write someone a conversation. Right after submitting the message I close the website and go to sleep. No other user visits the website for the next 24 hours => no push message will be sent during this time, correct?
I know that the chance of that happening is small, but push messages definitely could arrive with a delay.
I may implement that as a 3rd option in the dropdown, so the admins can decide own their own.

**Comment by TimWolla** [comment]
> no push message will be sent during this time, correct?

Yes. You can improve the reliability using [`BackgroundQueueHandler::forceCheck()`](https://github.com/WoltLab/WCF/blob/d6d86a03638c9028d418e8511d6d1827763fe373/wcfsetup/install/files/lib/system/background/BackgroundQueueHandler.class.php#L24-L30). This method is available in WSC 3.0 and was improved in WSC 3.1.

Generally you are encouraged to perform any long running operations that are not essential for the current request / response using the background queue. Say a request triggers 5 different notifications, this boils down to 5 requests to your server. For every request an TLS handshake needs to be performed, because the sessions are not re-used (I don't even know whether this is possible with PHP). Depending on the performance of your backend this is easily 100ms per request or half a second for all notifications. Add this to the usual processing time and the requests become noticeably slow.

**Comment by ChristopherWalz** [comment]
Alright, I will implement that as an option for the push mode and set it as the default.
